### ISSUE TITLE
Question about the two lists

### ISSUE THREAD

**Issue by BLKSerene** [pharos-alexandria/grk-stoplist#1]
Hi, many thanks for your list of stop words and the lemma list.
Since I'm going to use them in my own project, there's a minor issue I want to ask about. (Just to make sure that there's no misunderstanding)

Your repository has a CC0-1.0 license, but the file "grk_lemma.txt" says "This lemma list is provided "as is" and is free to use for any research and/or educational purposes. "
So is this file also licensed under CC0-1.0 or the license of this file is "provided "as is" and is free to use for any research and/or educational purposes."? (so not free for other purposes like commercial uses?)

Sorry for bothering you with such petty question.

**Comment by pharos-alexandria** [comment]
First of all: Sorry for the late answer! 
Please use the list as you like (also for commercial use). I made it for my own purposes, and it's far from perfect. I'll remove the line from grk_lemma.txt to avoid further confusion...

**Comment by BLKSerene** [comment]
Thanks a lot!
And by the way, if I want to give reference to your lists (stop-word list and lemma list), is it okay for me to cite the two lists with the name "grk-stoplist" (or you may pick a more suitable repository name for the two lists, since it includes both a stop-word list and a lemma list)?
And I suppose that the lemma list is also for ancient greek, not modern greek?

**Comment by pharos-alexandria** [comment]
For the lemma list (it is ancient greek) I only reformatted the list here: http://liris.cnrs.fr/dire/wiki/lib/exe/fetch.php?media=biblindex_lemmata.zip (as stated in the header of the file) to use it in AntConc (if I remember correctly), so it's maybe better to cite this directly. Regarding ancient greek lemma list you should maybe also look at the CLTK and for the stoplist at Voyant Tools...

**Comment by BLKSerene** [comment]
Thanks!
